language: scala

before_install:
  - curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh

install:
  - jabba install "$TRAVIS_JDK" && jabba use "$_" && java -Xmx32m -version

script:
  - sbt test

env:
  global:
    - TRAVIS_JDK=adopt@1.8-0

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt
